from Graph import Graph
from Node import Node
from Edge import Edge

# people/resources involved
nodes = [Node('Alyssa Bradshaw'), Node('Samuil Donchev'), Node('Maya Grant'), Node('Cornell Horne'),
         Node('Jorge Jimenez'), Node('Jacob Lozano'), Node('Raefa Malik'), Node('David Medina'),
         Node('Linda Nguessan'), Node('Charmaine Nieves'), Node('Omolola Okesanjo'), Node('Diana Pham'),
         Node('Adia Radecka'), Node('Joshua Sekyere'), Node('Ilalee Harrison'), Node('Ayoub Ellouzi'),
         Node('Trang Nguyen'), Node('Dr. Golecki'), Node('Professor Siggelkoe'), Node('SRT')]

# Displays the connection between teacher and student
edges = [
    # McKibbens
    Edge('SRT', 'Samuil Donchev', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Alyssa Bradshaw', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Maya Grant', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Cornell Horne', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Jorge Jimenez', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Jacob Lozano', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Raefa Malik', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'David Medina', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Linda Nguessan', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Charmaine Nieves', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Omolola Okesanjo', 'McKibbens Muscle', 'blue'),
    Edge('Samuil Donchev', 'Diana Pham', 'McKibbens Muscle', 'blue'),
    Edge('Dr. Golecki', 'Adia Radecka', 'McKibbens Muscle', 'blue'),
    Edge('Omolola Okesanjo', 'Joshua Sekyere', 'McKibbens Muscle', 'blue'),
    Edge('Professor Siggelkoe', 'Ayoub Ellouzi', 'McKibbens Muscle', 'blue'),
    Edge('Professor Siggelkoe', 'Trang Nguyen', 'McKibbens Muscle', 'blue'),

    # Heat Sealable Fabric Brace or Folding Box
    Edge('Dr. Golecki', 'Alyssa Bradshaw', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Joshua Sekyere', 'Maya Grant', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Dr. Golecki', 'Cornell Horne', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Diana Pham', 'Jorge Jimenez', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Charmaine Nieves', 'Jacob Lozano', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('SRT', 'Jacob Lozano', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Diana Pham', 'David Medina', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Diana Pham', 'Charmaine Nieves', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Joshua Sekyere', 'Omolola Okesanjo', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Dr. Golecki', 'Diana Pham', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Dr. Golecki', 'Adia Radecka', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Dr. Golecki', 'Joshua Sekyere', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Professor Siggelkoe', 'Ayoub Ellouzi', 'Heat Sealable Fabric Brace or Folding Box', 'black'),
    Edge('Professor Siggelkoe', 'Trang Nguyen', 'Heat Sealable Fabric Brace or Folding Box', 'black'),

    # SDM Finger
    Edge('Adia Radecka', 'Alyssa Bradshaw', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Samuil Donchev', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Maya Grant', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Cornell Horne', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Jorge Jimenez', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Jorge Jimenez', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Jacob Lozano', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Jacob Lozano', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Raefa Malik', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Raefa Malik', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'David Medina', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'David Medina', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Linda Nguessan', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Linda Nguessan', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Charmaine Nieves', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Charmaine Nieves', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Omolola Okesanjo', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Omolola Okesanjo', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Diana Pham', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Diana Pham', 'SDM Finger', 'green'),
    Edge('Dr. Golecki', 'Adia Radecka', 'SDM Finger', 'green'),
    Edge('Alyssa Bradshaw', 'Joshua Sekyere', 'SDM Finger', 'green'),
    Edge('Adia Radecka', 'Joshua Sekyere', 'SDM Finger', 'green'),
    Edge('Samuil Donchev', 'Ayoub Ellouzi', 'SDM Finger', 'green'),
    Edge('Trang Nguyen', 'Ayoub Ellouzi', 'SDM Finger', 'green'),
    Edge('Samuil Donchev', 'Trang Nguyen', 'SDM Finger', 'green'),
    Edge('SRT', 'Trang Nguyen', 'SDM Finger', 'green'),

    # Motorized SDM Finger
    Edge('Alyssa Bradshaw', 'Alyssa Bradshaw', 'Motorized SDM Finger', 'red'),
    Edge('Alyssa Bradshaw', 'Samuil Donchev', 'Motorized SDM Finger', 'red'),
    Edge('Adia Radecka', 'Samuil Donchev', 'Motorized SDM Finger', 'red'),
    Edge('Adia Radecka', 'Jacob Lozano', 'Motorized SDM Finger', 'red'),
    Edge('Alyssa Bradshaw', 'Jacob Lozano', 'Motorized SDM Finger', 'red'),
    Edge('Adia Radecka', 'Adia Radecka', 'Motorized SDM Finger', 'red'),
    Edge('Professor Siggelkoe', 'Ayoub Ellouzi', 'Motorized SDM Finger', 'red'),
    Edge('Professor Siggelkoe', 'Trang Nguyen', 'Motorized SDM Finger', 'red'),

    # SIA Actuator
    Edge('Dr. Golecki', 'Alyssa Bradshaw', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Samuil Donchev', 'SIA Actuator', 'purple'),
    Edge('David Medina', 'Cornell Horne', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Jorge Jimenez', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'Jorge Jimenez', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Jacob Lozano', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'Jacob Lozano', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'David Medina', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'David Medina', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'Charmaine Nieves', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Charmaine Nieves', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'Omolola Okesanjo', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Omolola Okesanjo', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Diana Pham', 'SIA Actuator', 'purple'),
    Edge('Dr. Golecki', 'Adia Radecka', 'SIA Actuator', 'purple'),
    Edge('Adia Radecka', 'Joshua Sekyere', 'SIA Actuator', 'purple'),
    Edge('Alyssa Bradshaw', 'Joshua Sekyere', 'SIA Actuator', 'purple'),
    Edge('Professor Siggelkoe', 'Ayoub Ellouzi', 'SIA Actuator', 'purple'),
    Edge('Professor Siggelkoe', 'Trang Nguyen', 'SIA Actuator', 'purple'),

    # Capacitance Sensor
    Edge('Samuil Donchev', 'Alyssa Bradshaw', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'Samuil Donchev', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'Jorge Jimenez', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'Jacob Lozano', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'David Medina', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'Charmaine Nieves', 'Capacitance Sensor', 'brown'),
    Edge('Dr. Golecki', 'Omolola Okesanjo', 'Capacitance Sensor', 'brown'),
    Edge('Samuil Donchev', 'Diana Pham', 'Capacitance Sensor', 'brown'),
    Edge('Omolola Okesanjo', 'Joshua Sekyere', 'Capacitance Sensor', 'brown'),

    # Flex Sensor
    Edge('David Medina', 'Samuil Donchev', 'Flex Sensor', 'Orange'),
    Edge('Cornell Horne', 'Maya Grant', 'Flex Sensor', 'Orange'),
    Edge('Dr. Golecki', 'Cornell Horne', 'Flex Sensor', 'Orange'),
    Edge('David Medina', 'Jorge Jimenez', 'Flex Sensor', 'Orange'),
    Edge('Charmaine Nieves', 'Jacob Lozano', 'Flex Sensor', 'Orange'),
    Edge('SRT', 'Jacob Lozano', 'Flex Sensor', 'Orange'),
    Edge('SRT', 'Raefa Malik', 'Flex Sensor', 'Orange'),
    Edge('Dr. Golecki', 'David Medina', 'Flex Sensor', 'Orange'),
    Edge('Omolola Okesanjo', 'David Medina', 'Flex Sensor', 'Orange'),
    Edge('Dr. Golecki', 'Linda Nguessan', 'Flex Sensor', 'Orange'),
    Edge('Dr. Golecki', 'Charmaine Nieves', 'Flex Sensor', 'Orange'),
    Edge('Dr. Golecki', 'Omolola Okesanjo', 'Flex Sensor', 'Orange'),
    Edge('SRT', 'Diana Pham', 'Flex Sensor', 'Orange'),
    Edge('SRT', 'Joshua Sekyere', 'Flex Sensor', 'Orange'),
    Edge('Professor Siggelkoe', 'Ayoub Ellouzi', 'Flex Sensor', 'Orange'),
    Edge('Professor Siggelkoe', 'Trang Nguyen', 'Flex Sensor', 'Orange'),

    # Textile Bending Actuator
    Edge('Jorge Jimenez', 'Samuil Donchev', 'Textile Bending Actuator', 'pink'),
    Edge('Jacob Lozano', 'Cornell Horne', 'Textile Bending Actuator', 'pink'),
    Edge('David Medina', 'Cornell Horne', 'Textile Bending Actuator', 'pink'),
    Edge('Cornell Horne', 'Cornell Horne', 'Textile Bending Actuator', 'pink'),
    Edge('Jacob Lozano', 'Jorge Jimenez', 'Textile Bending Actuator', 'pink'),
    Edge('David Medina', 'Jorge Jimenez', 'Textile Bending Actuator', 'pink'),
    Edge('Jorge Jimenez', 'Jorge Jimenez', 'Textile Bending Actuator', 'pink'),
    Edge('SRT', 'Jacob Lozano', 'Textile Bending Actuator', 'pink'),
    Edge('David Medina', 'David Medina', 'Textile Bending Actuator', 'pink'),
    Edge('Jacob Lozano', 'David Medina', 'Textile Bending Actuator', 'pink'),
    Edge('Jacob Lozano', 'Charmaine Nieves', 'Textile Bending Actuator', 'pink'),
    Edge('Charmaine Nieves', 'Charmaine Nieves', 'Textile Bending Actuator', 'pink'),
    Edge('Jacob Lozano', 'Omolola Okesanjo', 'Textile Bending Actuator', 'pink'),
    Edge('Omolola Okesanjo', 'Omolola Okesanjo', 'Textile Bending Actuator', 'pink'),
    Edge('SRT', 'Diana Pham', 'Textile Bending Actuator', 'pink'),
    Edge('David Medina', 'Diana Pham', 'Textile Bending Actuator', 'pink'),

]

graph = Graph(nodes, edges)

graph.show_graph()
